#!/bin/sh
OPTS=""

chown root:root /etc/sudoers.d/pollux

if [ -f "$D/etc/lighttpd.conf" ]; then
    echo "" >> "$D/etc/lighttpd.conf"
    echo "### Following added by pollux_config package on" `date` >> "$D/etc/lighttpd.conf"
    echo 'include_shell "/usr/bin/pollux_config_lighttpdconf"' >> "$D/etc/lighttpd.conf"

    if [ -z "$D" ] && [ -f "$D/lib/systemd/system/lighttpd.service" ]; then
        systemctl restart lighttpd.service
    fi
fi

